
services:
- type: web
  name: Course-Crafter
  runtime: python
  repo: https://github.com/Namany27/Course-Crafter
  plan: free
  region: oregon
  buildCommand: |
  modal token new
  pip install -r requirements.txt
    
  startCommand: python gradio_ui.py
  autoDeployTrigger: commit
version: "1"
