
services:
- type: web
  name: Course-Crafter
  runtime: python
  repo: https://github.com/Namany27/Course-Crafter
  plan: free
  region: oregon
  buildCommand: |
    python
    pip install -r requirements.txt
    modal token set --token-id ak-HedtiE3jD6vlbQc5STLxdQ --token-secret as-1sE5SzrIscgg3WzjsmlnwO 
  startCommand: python gradio_ui.py
  autoDeployTrigger: commit
version: "1"
